[package]
name = "pico2-uac1-loopback"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.10.0", features = ["executor-thread", "platform-cortex-m"] }
embassy-futures = "0.1.2"
embassy-rp = { version = "0.10.0", features = ["binary-info", "critical-section-impl", "imagedef-secure-exe", "rp235xa", "time-driver"] }
embassy-sync = "0.8.0"
embassy-usb = { version = "0.6.0", default-features = false, features = ["max-handler-count-1", "max-interface-count-4"] }
embedded-test = "0.7.1"
panic-halt = "1"
static_cell = "2"

[lib]
harness = false

[[bin]]
name = "pico2-uac1-loopback"
path = "src/main.rs"
harness = false
test = false

[profile.dev]
codegen-units = 1
debug = 2
incremental = false
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
