[build]
target = "thumbv8m.main-none-eabihf"

[alias]
loopback-check = "run --target x86_64-pc-windows-msvc -p loopback-check"
loopback-check-build = "build --target x86_64-pc-windows-msvc -p loopback-check"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP235x"
rustflags = [
  "-C",
  "target-cpu=cortex-m33",
  "-L",
  ".",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tembedded-test.x",
]
